spring:
  application:
    name: ecommerce-api
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  
app:
  jwt:
    access-token-ttl: 15m
    refresh-token-ttl: 7d
