spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  jwt:
    secret: ${APP_JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ecommerce-api